# Generated by Django 5.0 on 2024-07-31 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalanceopenings',
            name='leave_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms_app.leavetype', verbose_name='Leave Type'),
        ),
    ]
