# Generated by Django 5.0 on 2024-07-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0002_alter_leavebalanceopenings_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='text_color_hex',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Text Color Hex Code'),
        ),
    ]
