# Generated by Django 5.0 on 2024-08-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0003_leavetype_text_color_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='endDayChoice',
            field=models.CharField(choices=[('1', 'Full Day'), ('2', 'First Half (Morning)'), ('3', 'Second Half (Afternoon)')], default='1', max_length=20, verbose_name='End Day Choice'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='startDayChoice',
            field=models.CharField(choices=[('1', 'Full Day'), ('2', 'First Half (Morning)'), ('3', 'Second Half (Afternoon)')], default='1', max_length=20, verbose_name='Start Day Choice'),
        ),
    ]
