# Generated by Django 5.0 on 2024-08-02 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0004_leaveapplication_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_applications', to='hrms_app.leavetype', verbose_name='Leave Type'),
        ),
    ]
