# Generated by Django 5.0 on 2024-08-02 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0005_leaveapplication_leave_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetails',
            name='correspondence_address',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='permanent_address',
        ),
        migrations.AddField(
            model_name='correspondingaddress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corres_addresses', to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='parmanentaddress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permanent_addresses', to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('pending_cancellation', 'Pending Cancellation')], default='pending', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='tourstatuslog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('extended', 'Extended')], default='pending', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='usertour',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('extended', 'Extended')], default='pending', max_length=50, verbose_name='Status'),
        ),
    ]
