# Generated by Django 5.0 on 2024-08-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0006_remove_personaldetails_correspondence_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reason'),
        ),
    ]
