# Generated by Django 5.0 on 2024-08-26 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0008_usertour_end_time_usertour_slug_usertour_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertour',
            name='applied_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to=settings.AUTH_USER_MODEL, verbose_name='Applied By'),
        ),
    ]
