# Generated by Django 5.0 on 2024-08-26 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0009_alter_usertour_applied_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourstatuslog',
            name='action',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Action'),
        ),
        migrations.AddField(
            model_name='tourstatuslog',
            name='action_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Action By'),
        ),
        migrations.AddField(
            model_name='tourstatuslog',
            name='action_by_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Action By Email'),
        ),
        migrations.AddField(
            model_name='tourstatuslog',
            name='action_by_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Action By Name'),
        ),
    ]
