# Generated by Django 5.0 on 2024-08-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0010_tourstatuslog_action_tourstatuslog_action_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertour',
            name='createdAt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='usertour',
            name='updatedAt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated At'),
        ),
    ]
