# Generated by Django 5.0 on 2024-08-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0011_usertour_createdat_usertour_updatedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertour',
            name='approval_type',
            field=models.CharField(blank=True, choices=[('pre approval', 'Pre Approval'), ('post approval', 'Post Approval')], max_length=100, null=True, verbose_name='Approval Type'),
        ),
    ]
