# Generated by Django 5.0 on 2024-08-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0012_usertour_approval_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='is_submitted',
            field=models.BooleanField(default=False, help_text='This is a boolean flag to handle if regularization is submitted or not.', verbose_name='Is Submitted'),
        ),
    ]
