# Generated by Django 5.0 on 2024-08-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0013_attendancelog_is_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertour',
            name='createdAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='usertour',
            name='updatedAt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Updated At'),
        ),
    ]
