# Generated by Django 5.0 on 2024-08-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0014_alter_usertour_createdat_alter_usertour_updatedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertour',
            name='extended_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Extended End Date'),
        ),
        migrations.AlterField(
            model_name='tourstatuslog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('extended', 'Extended'), ('pending_cancellation', 'Pending Cancellation')], default='pending', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='usertour',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('extended', 'Extended'), ('pending_cancellation', 'Pending Cancellation')], default='pending', max_length=50, verbose_name='Status'),
        ),
    ]
