# Generated by Django 5.0 on 2024-09-06 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0015_usertour_extended_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pd_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='cug_mobile_number',
            field=models.CharField(blank=True, help_text='Employee compnay provided mobile number if any', max_length=15, verbose_name='Company Mobile Number'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='dof',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Final Settlement'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='dor',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Resignation'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='marriage_ann',
            field=models.DateField(blank=True, null=True, verbose_name='Marriage Anniversary'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pd_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='reg_status',
            field=models.CharField(blank=True, choices=[('early going', 'Early Going'), ('late coming', 'Late Coming'), ('mis punching', 'Mis Punching')], max_length=20, null=True, verbose_name='Regularization Status'),
        ),
        migrations.AlterField(
            model_name='attendancesetting',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='updatedAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='leavebalanceopenings',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='alt_mobile_number',
            field=models.CharField(blank=True, help_text='Employee person alternate mobile number', max_length=15, verbose_name='Alternative Mobile Number'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='ann_date',
            field=models.DateField(blank=True, null=True, verbose_name='Job Anniversary'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='CTC'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='employee_code',
            field=models.CharField(help_text='Enter the employee code with company shor code prefix, For example: KMPCL-65', max_length=100, unique=True, verbose_name='Employee Code'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='mobile_number',
            field=models.CharField(help_text='Employee person mobile number', max_length=15, unique=True, verbose_name='Mobile Number'),
        ),
    ]
