# Generated by Django 5.0 on 2024-09-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0017_formprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='formprogress',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='formprogress',
            name='status',
            field=models.CharField(choices=[('in-progress', 'In Progress'), ('completed', 'Completed')], default='in-progress', max_length=20),
        ),
        migrations.AddField(
            model_name='formprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Updated At'),
        ),
    ]
