# Generated by Django 4.2.16 on 2024-09-16 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0018_formprogress_created_at_formprogress_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='employee_images/')),
                ('employee_code', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('profile_complete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Employee Image',
                'verbose_name_plural': 'Employee Images',
                'db_table': 'tbl_employee_images',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='employee_code',
            field=models.CharField(help_text='Enter the employee code with company shor code prefix, For example: 65', max_length=100, unique=True, verbose_name='Employee Code'),
        ),
        migrations.AlterField(
            model_name='salarydetails',
            name='conveyance_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salarydetails',
            name='medical_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sent Mail',
                'verbose_name_plural': 'Sent Mails',
                'db_table': 'tbl_sent_email',
                'managed': True,
            },
        ),
    ]
