# Generated by Django 4.2.16 on 2024-09-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0019_employeeimage_alter_personaldetails_employee_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeClassMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=100, unique=True)),
                ('class_index', models.IntegerField(unique=True)),
            ],
        ),
    ]
