# Generated by Django 4.2.16 on 2024-09-24 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0020_employeeclassmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('on role', 'On-Role'), ('off role', 'Off-Role')], max_length=50, verbose_name='Role Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'tbl_role',
            },
        ),
        migrations.AlterModelOptions(
            name='parmanentaddress',
            options={'managed': True, 'verbose_name': 'Permanent Address', 'verbose_name_plural': 'Permanent Addresses'},
        ),
        migrations.AddField(
            model_name='shifttiming',
            name='break_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Break Duration (minutes)'),
        ),
        migrations.AddField(
            model_name='shifttiming',
            name='break_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Break End Time'),
        ),
        migrations.AddField(
            model_name='shifttiming',
            name='break_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Break Start Time'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='cug_mobile_number',
            field=models.CharField(blank=True, help_text='Employee company provided mobile number if any', max_length=15, verbose_name='Company Mobile Number'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='employee_code',
            field=models.CharField(help_text='Enter the employee code with company short code prefix, For example: 65', max_length=100, unique=True, verbose_name='Employee Code'),
        ),
        migrations.AlterField(
            model_name='shifttiming',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms_app.role', verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='shifttiming',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms_app.role', verbose_name='Role'),
        ),
    ]
