# Generated by Django 4.2.16 on 2025-01-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0021_remove_attendancelog_is_late_coming_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Unique key for identifying the application setting (e.g., 'REGULARIZATION_LIMIT').", max_length=255, unique=True, verbose_name='Setting Key')),
                ('value', models.CharField(help_text="Value associated with the setting (e.g., '3' for the maximum number of times allowed).", max_length=255, verbose_name='Setting Value')),
                ('description', models.TextField(blank=True, help_text='Optional description of what this setting controls.', null=True, verbose_name='Description')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update to this setting.', verbose_name='Last Updated')),
                ('beyond_policy', models.BooleanField(default=True, help_text='Indicates whether this setting is allowed beyond policy or not.', verbose_name='Allowed Beyond Policy')),
            ],
            options={
                'verbose_name': 'Application Setting',
                'verbose_name_plural': 'Application Settings',
                'ordering': ['key'],
            },
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='salutation',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.'), ('Er.', 'Er.')], default='Mr.', help_text='Select the salutation for the employee.', max_length=10, verbose_name='Salutation'),
        ),
    ]
