# Generated by Django 4.2.16 on 2024-10-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0021_role_alter_parmanentaddress_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField(help_text='Enter the start date and time for the transaction log.', verbose_name='From Date')),
                ('to_date', models.DateTimeField(help_text='Enter the end date and time for the transaction log.', verbose_name='To Date')),
                ('serial_number', models.CharField(help_text='Enter the device serial number.', max_length=50, unique=True, verbose_name='Serial Number')),
                ('username', models.CharField(help_text='Enter the API username for authentication.', max_length=30, verbose_name='Username')),
                ('password', models.CharField(help_text='Enter the API password for authentication.', max_length=50, verbose_name='Password')),
            ],
            options={
                'verbose_name': 'Device Information',
                'verbose_name_plural': 'Device Information Records',
                'db_table': 'tbl_device_information',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='leavetype',
            name='consecutive_restriction',
            field=models.BooleanField(default=False, help_text='Check if consecutive leave applications are not allowed for this leave type.', verbose_name='Consecutive Leave Restriction'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='restricted_after_leave_types',
            field=models.ManyToManyField(blank=True, help_text='Select leave types after which this leave type cannot be applied consecutively.', related_name='restricted_by_leave_types', to='hrms_app.leavetype', verbose_name='Restricted After Leave Types'),
        ),
        migrations.CreateModel(
            name='LeaveDayChoiceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day_choice', models.CharField(choices=[('1', 'Full Day'), ('2', 'First Half (Morning)'), ('3', 'Second Half (Afternoon)')], max_length=20, verbose_name='Start Day Choice')),
                ('end_day_choice', models.CharField(choices=[('1', 'Full Day'), ('2', 'First Half (Morning)'), ('3', 'Second Half (Afternoon)')], max_length=20, verbose_name='End Day Choice')),
                ('adjustment_value', models.FloatField(verbose_name='Adjustment Value')),
            ],
            options={
                'verbose_name': 'Leave Day Choice Adjustment',
                'verbose_name_plural': 'Leave Day Choice Adjustments',
                'unique_together': {('start_day_choice', 'end_day_choice')},
            },
        ),
    ]
