# Generated by Django 4.2.16 on 2024-10-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0022_deviceinformation_leavetype_consecutive_restriction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinformation',
            name='api_link',
            field=models.URLField(default='http://1.22.197.176:99/iclock/WebAPIService.asmx', help_text='Enter the API link for the device.', verbose_name='API Link'),
        ),
    ]
