# Generated by Django 4.2.16 on 2025-02-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0022_appsetting_alter_personaldetails_salutation'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='attachment',
            field=models.FileField(blank=True, help_text='Upload an image or PDF file (optional).', null=True, upload_to='leave_attachments/', verbose_name='Attachment'),
        ),
    ]
