# Generated by Django 4.2.16 on 2025-04-05 05:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hrms_app', '0023_leaveapplication_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short and clear title of the announcement.', max_length=255, verbose_name='Title')),
                ('content', models.TextField(help_text='Full description or body of the announcement.', verbose_name='Content')),
                ('type', models.CharField(choices=[('general', 'General'), ('policy', 'Policy Update'), ('event', 'Event'), ('holiday', 'Holiday Notice'), ('alert', 'Urgent/Alert')], default='general', help_text='Category/type of the announcement for filtering.', max_length=20, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='Date from which the announcement becomes visible.', verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='Date after which the announcement is no longer shown. Leave blank for indefinite.', null=True, verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, help_text='Only active announcements will be shown to users.', verbose_name='Is Active')),
                ('pinned', models.BooleanField(default=False, help_text='Pinned announcements appear at the top.', verbose_name='Pin Announcement')),
                ('audience_roles', models.ManyToManyField(blank=True, help_text='Limit visibility to specific user groups/roles.', to='auth.group', verbose_name='Audience Roles')),
            ],
            options={
                'verbose_name': 'HR Announcement',
                'verbose_name_plural': 'HR Announcements',
                'db_table': 'tbl_announcement',
                'ordering': ['-pinned', '-start_date', '-created_at'],
            },
        ),
    ]
