# Generated by Django 4.2.16 on 2024-10-04 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0023_deviceinformation_api_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this location, generated automatically.', primary_key=True, serialize=False, verbose_name='Unique Identifier')),
                ('location_name', models.CharField(help_text='Enter the name of the location (e.g., Head Office, Cluster Office, etc.)', max_length=100, verbose_name='Location Name')),
                ('office_type', models.CharField(choices=[('head_office', 'Head Office'), ('cluster_office', 'Cluster Office'), ('mcc', 'MCC'), ('bmc', 'BMC'), ('mpp', 'BMC')], help_text='Specify the type of office (Head Office, Cluster Office, MCC, BMC, MPP).', max_length=50, verbose_name='Office Type')),
                ('address', models.TextField(help_text='Enter the complete address of the location.', verbose_name='Address')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Enter the latitude of the location.', max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Enter the longitude of the location.', max_digits=9, null=True, verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was last updated.', verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Office Location',
                'verbose_name_plural': 'Office Locations',
                'ordering': ['location_name'],
            },
        ),
        migrations.AddField(
            model_name='deviceinformation',
            name='device_location',
            field=models.ForeignKey(blank=True, help_text='Where this device is located. For ex: - MCC or Cluster office location', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms_app.officelocation', verbose_name='Device Location'),
        ),
    ]
