# Generated by Django 4.2.16 on 2025-04-07 06:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0024_hrannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_personal_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='The email address to which the OTP was sent.', max_length=254, verbose_name='Email Address')),
                ('otp', models.CharField(help_text='The one-time password sent to the email.', max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', message='OTP must be a 6-digit number.')], verbose_name='OTP')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the OTP was generated.', verbose_name='Created At')),
                ('verified', models.BooleanField(default=False, help_text='Indicates whether the OTP was successfully verified.', verbose_name='Is Verified')),
                ('user', models.ForeignKey(help_text='The user this OTP is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Email OTP',
                'verbose_name_plural': 'Email OTPs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'email'], name='hrms_app_em_user_id_7276b1_idx'), models.Index(fields=['otp'], name='hrms_app_em_otp_c13098_idx'), models.Index(fields=['created_at'], name='hrms_app_em_created_f3c8e5_idx')],
                'unique_together': {('email', 'otp')},
            },
        ),
    ]
