# Generated by Django 4.2.16 on 2024-10-04 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0024_officelocation_deviceinformation_device_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='device_location',
            field=models.ForeignKey(blank=True, help_text='Where this device is located. For ex: - MCC or Cluster office location', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms_app.officelocation', verbose_name='Device Location'),
        ),
    ]
