# Generated by Django 4.2.16 on 2025-04-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0025_customuser_is_personal_email_verified_emailotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date when the office was closed', unique=True, verbose_name='Closure Date')),
                ('closure_type', models.CharField(choices=[('full', 'Full Day'), ('half', 'Half Day'), ('custom', 'Custom')], help_text='Was it a full-day, half-day (e.g., post-lunch), or custom closure?', max_length=10, verbose_name='Type of Closure')),
                ('short_code', models.CharField(default='SR', help_text='Used to denote the attendance', max_length=10, verbose_name='Short Cde')),
                ('reason', models.TextField(help_text='Provide a short explanation for the closure', verbose_name='Reason for Closure')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this entry was created', verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Office Closure',
                'verbose_name_plural': 'Office Closures',
                'db_table': 'tbl_office_closer',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='tbl_office__date_3962dc_idx')],
            },
        ),
    ]
