# Generated by Django 4.2.16 on 2025-04-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0026_officeclosure'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='leave_address',
            field=models.CharField(blank=True, help_text='Please provide the address.', max_length=100, null=True, verbose_name='Leave Address'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='alt_mobile_number',
            field=models.CharField(blank=True, help_text='Enter an alternate mobile number for the employee (optional).', max_length=15, verbose_name='Emergency Contact Number'),
        ),
    ]
