# Generated by Django 4.2.16 on 2024-10-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0026_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='att_status_short_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Short Code'),
        ),
    ]
