# Generated by Django 4.2.16 on 2025-04-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0027_leaveapplication_leave_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='regularized_backend',
            field=models.BooleanField(default=False, help_text='Indicate if this entry is regularized from backend.', verbose_name='Backend Regularized'),
        ),
    ]
