# Generated by Django 4.2.16 on 2024-10-06 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0027_attendancelog_att_status_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='default_allocation',
            field=models.FloatField(blank=True, help_text='Set the default number of days allocated for this leave type.', null=True, verbose_name='Default Allocation'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='allowed_days_per_year',
            field=models.FloatField(blank=True, help_text='Specify the total number of days allowed for this leave type per year.', null=True, verbose_name='Allowed Days Per Year'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='color_hex',
            field=models.CharField(blank=True, help_text='Enter a hex color code to represent this leave type in the system.', max_length=7, null=True, verbose_name='Color Hex Code'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='created_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when this leave type was created (automatically set).', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who created this leave type (set automatically).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leave_types', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='leave_fy_end',
            field=models.DateField(blank=True, help_text='Define the end of the financial year for leave calculations (optional).', null=True, verbose_name='Leave FY End'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='leave_fy_start',
            field=models.DateField(blank=True, help_text='Define the start of the financial year for leave calculations (optional).', null=True, verbose_name='Leave FY Start'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='leave_type',
            field=models.CharField(choices=[('Unpaid Leave (LWP)', 'Unpaid Leave (LWP)'), ('Casual Leave (CL)', 'Casual Leave (CL)'), ('Sick Leave (SL)', 'Sick Leave (SL)'), ('Earned Leave (EL)', 'Earned Leave (EL)'), ('Maternity Leave (ML)', 'Maternity Leave (ML)'), ('Comp OFF', 'Comp OFF (CO)')], help_text='Select the type of leave (e.g., Sick Leave, Casual Leave). This must be unique.', max_length=100, unique=True, verbose_name='Leave Type'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='leave_type_short_code',
            field=models.CharField(blank=True, help_text='Provide a short code for the leave type (optional). This must be unique if provided.', max_length=100, null=True, unique=True, verbose_name='Leave Type Short Code'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='max_days_limit',
            field=models.FloatField(blank=True, help_text='Set the maximum number of consecutive days that can be taken for this leave type.', null=True, verbose_name='Maximum Days Limit'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='min_days_limit',
            field=models.FloatField(blank=True, help_text='Set the minimum number of consecutive days that can be taken for this leave type.', null=True, verbose_name='Minimum Days Limit'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='min_notice_days',
            field=models.FloatField(blank=True, help_text='Specify the minimum number of days notice required before applying for this leave.', null=True, verbose_name='Minimum Notice Days'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='text_color_hex',
            field=models.CharField(blank=True, help_text='Enter a hex color code for the text color to be used with this leave type.', max_length=7, null=True, verbose_name='Text Color Hex Code'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when this leave type was last updated (automatically set).', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='The user who last updated this leave type (set automatically).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_leave_types', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
    ]
