# Generated by Django 4.2.16 on 2025-04-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0028_attendancelog_regularized_backend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='regularized_backend',
            field=models.BooleanField(blank=True, default=False, help_text='Indicate if this entry is regularized from backend.', null=True, verbose_name='Backend Regularized'),
        ),
    ]
