# Generated by Django 4.2.16 on 2024-10-08 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0028_leavetype_default_allocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalanceopenings',
            name='created_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when this leave balance record was created.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='leavebalanceopenings',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who created this leave balance record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leave_balances', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='leavebalanceopenings',
            name='leave_type',
            field=models.ForeignKey(help_text='The type of leave for which the balance is being recorded.', null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms_app.leavetype', verbose_name='Leave Type'),
        ),
        migrations.AlterField(
            model_name='leavebalanceopenings',
            name='no_of_leaves',
            field=models.FloatField(blank=True, help_text='The total number of leaves allocated to the user for this leave type.', null=True, verbose_name='Number of Leaves'),
        ),
        migrations.AlterField(
            model_name='leavebalanceopenings',
            name='remaining_leave_balances',
            field=models.FloatField(blank=True, help_text='The remaining balance of leaves available to the user for this leave type.', null=True, verbose_name='Remaining Leave Balance'),
        ),
        migrations.AlterField(
            model_name='leavebalanceopenings',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when this leave balance record was last updated.', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='leavebalanceopenings',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='The user who last updated this leave balance record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_leave_balances', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='leavebalanceopenings',
            name='user',
            field=models.ForeignKey(help_text='The user for whom this leave balance is being recorded.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='leavebalanceopenings',
            name='year',
            field=models.PositiveIntegerField(default=2024, help_text='The year for which the leave balance applies.', verbose_name='Year'),
        ),
    ]
