# Generated by Django 4.2.16 on 2025-11-28 04:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0031_alter_attendancelog_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='applicable_users',
            field=models.ManyToManyField(blank=True, help_text='Leave blank to apply to all users', related_name='applicable_holidays', to=settings.AUTH_USER_MODEL, verbose_name='Applicable Users'),
        ),
    ]
