# Generated by Django 4.2.16 on 2026-01-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0032_holiday_applicable_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalanceopenings',
            name='year',
            field=models.PositiveIntegerField(default=2026, help_text='The year for which the leave balance is applicable.', verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='leave_type',
            field=models.CharField(default='', help_text='Select the type of leave (e.g., Sick Leave, Casual Leave). This must be unique.', max_length=100, unique=True, verbose_name='Leave Type'),
        ),
    ]
