# Generated by Django 4.2.16 on 2026-01-20 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0033_alter_leavebalanceopenings_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavetype',
            options={'verbose_name': 'Leave Type', 'verbose_name_plural': 'Leave Types'},
        ),
        migrations.AddField(
            model_name='leavetype',
            name='accrual_period',
            field=models.CharField(choices=[('NONE', 'No Accrual'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='YEARLY', max_length=10, verbose_name='Accrual Period'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='accrual_quantity',
            field=models.FloatField(blank=True, help_text='Leave allocated per accrual period.', null=True, verbose_name='Accrual Quantity'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='allow_carry_forward',
            field=models.BooleanField(default=False, verbose_name='Allow Carry Forward'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='allow_half_day',
            field=models.BooleanField(default=False, verbose_name='Allow Half Day'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='expiry_policy',
            field=models.CharField(choices=[('NONE', 'No Expiry'), ('PERIOD_END', 'Expire at Period End'), ('FY_END', 'Expire at Financial Year End')], default='NONE', max_length=15, verbose_name='Expiry Policy'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='half_day_value',
            field=models.FloatField(default=0.5, help_text='Applicable only for day-based leaves.', verbose_name='Half Day Value'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='leave_unit',
            field=models.CharField(choices=[('DAY', 'Day'), ('HOUR', 'Hour'), ('MINUTE', 'Minute')], default='DAY', help_text='Defines whether leave is counted in days, hours, or minutes.', max_length=10, verbose_name='Leave Unit'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='max_carry_forward',
            field=models.FloatField(blank=True, null=True, verbose_name='Max Carry Forward'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='max_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum duration allowed (based on leave unit).', null=True, verbose_name='Maximum Duration'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='min_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum duration allowed (based on leave unit).', null=True, verbose_name='Minimum Duration'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='must_apply_within_accrual_period',
            field=models.BooleanField(default=False, help_text='If enabled, leave must be applied within the same accrual period (e.g. short leave must be used in the same month).', verbose_name='Must Apply Within Same Period'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='allowed_days_per_year',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='color_hex',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='consecutive_restriction',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leave_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='default_allocation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='half_day_short_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Half Day Short Code'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='leave_fy_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='leave_fy_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='leave_type',
            field=models.CharField(help_text='Name of the leave type (e.g. Sick Leave, Short Leave).', max_length=100, unique=True, verbose_name='Leave Type'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='leave_type_short_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Leave Short Code'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='max_days_limit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='min_days_limit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='min_notice_days',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='restricted_after_leave_types',
            field=models.ManyToManyField(blank=True, related_name='restricted_by_leave_types', to='hrms_app.leavetype'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='text_color_hex',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_leave_types', to=settings.AUTH_USER_MODEL),
        ),
    ]
