# Generated by Django 4.2.16 on 2026-01-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0034_alter_leavetype_options_leavetype_accrual_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalanceopenings',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this leave balance is active and can be used for applying leave.', verbose_name='Is Active'),
        ),
    ]
