# Generated by Django 4.2.16 on 2026-01-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0035_leavebalanceopenings_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='from_time',
            field=models.TimeField(blank=True, help_text='Start time for Short Leave', null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='to_time',
            field=models.TimeField(blank=True, help_text='End time for Short Leave', null=True),
        ),
    ]
