# Generated by Django 4.2.16 on 2026-02-03 04:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0036_leaveapplication_from_time_leaveapplication_to_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavebalanceopenings',
            options={'ordering': ['-year', '-month'], 'verbose_name': 'Leave Balance', 'verbose_name_plural': 'Leave Balances'},
        ),
        migrations.AlterUniqueTogether(
            name='leavebalanceopenings',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='leavebalanceopenings',
            name='allocated',
            field=models.FloatField(default=0, help_text='Total allocated for this period.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='leavebalanceopenings',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Required only for monthly accrued leaves (1-12).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='leavebalanceopenings',
            name='used',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='leavebalanceopenings',
            name='closing_balance',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='leavebalanceopenings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='leavebalanceopenings',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leave_balances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leavebalanceopenings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='leavebalanceopenings',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='hrms_app.leavetype'),
        ),
        migrations.AlterField(
            model_name='leavebalanceopenings',
            name='opening_balance',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='leavebalanceopenings',
            name='remaining_leave_balances',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='leavebalanceopenings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leavebalanceopenings',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_leave_balances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leavebalanceopenings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leavebalanceopenings',
            name='year',
            field=models.PositiveIntegerField(default=2026),
        ),
        migrations.AddConstraint(
            model_name='leavebalanceopenings',
            constraint=models.UniqueConstraint(fields=('user', 'leave_type', 'year', 'month'), name='unique_leave_balance_period'),
        ),
    ]
