# Generated by Django 4.2.16 on 2026-03-11 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0037_alter_leavebalanceopenings_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePolicyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(help_text='Date from which this policy version is active.', verbose_name='Effective From')),
                ('effective_to', models.DateField(blank=True, help_text='Date until which this policy version is active. Leave blank for the currently active version.', null=True, verbose_name='Effective To')),
                ('annual_entitlement', models.FloatField(help_text='Total days credited per year. e.g. CL=10, SL=10, EL=30', verbose_name='Annual Entitlement (Days)')),
                ('accrual_period', models.CharField(choices=[('none', 'No Accrual'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='yearly', help_text='How often leave is credited. EL=quarterly, CL/SL=yearly.', max_length=20, verbose_name='Accrual Period')),
                ('calculation_period', models.CharField(choices=[('calendar_year', 'Calendar Year (Jan–Dec)'), ('financial_year', 'Financial Year (Apr–Mar)')], default='calendar_year', help_text='CL/SL use Calendar Year; EL uses Financial Year.', max_length=20, verbose_name='Calculation Period')),
                ('min_notice_days', models.FloatField(default=1, help_text='How many days in advance must the leave be applied. CL/SL=1, EL=7.', verbose_name='Minimum Notice Days')),
                ('max_consecutive_days', models.FloatField(blank=True, help_text='Max days in a single application. CL=5, EL=no limit.', null=True, verbose_name='Max Consecutive Days')),
                ('min_days_per_application', models.FloatField(blank=True, help_text='Minimum days per single application. EL=3.', null=True, verbose_name='Min Days Per Application')),
                ('max_spells_per_year', models.IntegerField(blank=True, help_text='Max number of separate applications per year. EL=5.', null=True, verbose_name='Max Spells Per Year')),
                ('allow_half_day', models.BooleanField(default=False, help_text='CL=True (half-day allowed), EL=restricted (prefix/suffix only).', verbose_name='Allow Half Day')),
                ('half_day_only_as_prefix_suffix', models.BooleanField(default=False, help_text='EL-specific: half-day EL is only permitted as a prefix or suffix to more than one day of EL.', verbose_name='Half Day Only as Prefix / Suffix')),
                ('retrospective_application_working_days', models.IntegerField(default=3, help_text='For urgent/unforeseen leave: application must be submitted within this many working days after the absence. CL/SL=3.', verbose_name='Retrospective Application Window (Working Days)')),
                ('requires_confirmation', models.BooleanField(default=False, help_text='EL=True: only confirmed employees can avail.', verbose_name='Requires Confirmation (Post-Probation)')),
                ('cannot_combine_with_any', models.BooleanField(default=False, help_text='CL=True: CL cannot be clubbed with any other leave type.', verbose_name='Cannot Combine With Any Other Leave')),
                ('allow_carry_forward', models.BooleanField(default=False, verbose_name='Allow Carry Forward')),
                ('max_carry_forward_days', models.FloatField(blank=True, help_text='EL=300. Excess lapses automatically at year end.', null=True, verbose_name='Max Carry Forward Days')),
                ('max_accumulation_days', models.FloatField(blank=True, help_text='SL=180, EL=300. Hard ceiling on total balance.', null=True, verbose_name='Max Accumulation Days')),
                ('lapse_unused_at_period_end', models.BooleanField(default=False, help_text='CL=True (unused CL lapses Dec 31).', verbose_name='Lapse Unused at Period End')),
                ('is_encashable', models.BooleanField(default=False, verbose_name='Is Encashable')),
                ('encashment_max_times_per_year', models.IntegerField(blank=True, help_text='EL=2. Applicable only while in service.', null=True, verbose_name='Max Encashments Per Year')),
                ('encashment_min_days', models.FloatField(blank=True, help_text='EL=10 days minimum per encashment request.', null=True, verbose_name='Min Days Per Encashment')),
                ('encashment_min_balance_after', models.FloatField(blank=True, help_text='EL=30 days must remain after encashment.', null=True, verbose_name='Min Balance After Encashment')),
                ('encashable_on_separation', models.BooleanField(default=False, help_text='EL=True. SL=True (except misconduct termination).', verbose_name='Encashable on Separation')),
                ('encashment_triggers', models.JSONField(blank=True, default=list, help_text="List of triggers that allow encashment. e.g. ['separation','retirement','resignation','critical_health','disability','marriage']. EL also allows 'in_service'.", verbose_name='Encashment Triggers')),
                ('no_encashment_on_misconduct', models.BooleanField(default=False, help_text='SL=True: encashment blocked if terminated for misconduct.', verbose_name='No Encashment on Misconduct Termination')),
                ('allow_advance_leave', models.BooleanField(default=False, help_text='EL=True: up to max_advance_leave_days in advance with CA approval.', verbose_name='Allow Advance Leave')),
                ('max_advance_leave_days', models.FloatField(blank=True, help_text='EL=5 days advance.', null=True, verbose_name='Max Advance Leave Days')),
                ('max_short_leaves_per_month', models.IntegerField(blank=True, help_text='STL=2 per month.', null=True, verbose_name='Max Short Leaves Per Month')),
                ('max_short_leave_hours_per_occasion', models.FloatField(blank=True, help_text='STL=2 hours per occasion.', null=True, verbose_name='Max Short Leave Hours Per Occasion')),
                ('paternity_days_before_birth', models.IntegerField(blank=True, help_text='Paternity=7 days before expected delivery.', null=True, verbose_name='Days Before Birth Allowed')),
                ('paternity_days_after_birth', models.IntegerField(blank=True, help_text='Paternity=90 days (3 months) after birth.', null=True, verbose_name='Days After Birth Allowed')),
                ('paternity_max_times_in_tenure', models.IntegerField(blank=True, help_text='Paternity=2 times in entire tenure.', null=True, verbose_name='Max Times in Tenure')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('can_club_with', models.ManyToManyField(blank=True, help_text='Specific leave types this leave CAN be combined with. SL can club with EL in medical emergency.', related_name='clubbable_policies', to='hrms_app.leavetype', verbose_name='Can Club With')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policy_configs', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_versions', to='hrms_app.leavetype', verbose_name='Leave Type')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_policy_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Policy Config',
                'verbose_name_plural': 'Leave Policy Configs',
                'db_table': 'tbl_leave_policy_config',
                'ordering': ['-effective_from'],
                'managed': True,
                'indexes': [models.Index(fields=['leave_type', 'effective_from'], name='idx_policy_config_type_date')],
            },
        ),
        migrations.AddConstraint(
            model_name='leavepolicyconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True)), fields=('leave_type',), name='unique_active_policy_per_leave_type'),
        ),
    ]
