# Generated by Django 4.2.16 on 2026-06-23 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0038_leavepolicyconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourDateTimeChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_start_date', models.DateField(blank=True, null=True, verbose_name='Previous Start Date')),
                ('previous_start_time', models.TimeField(blank=True, null=True, verbose_name='Previous Start Time')),
                ('previous_end_date', models.DateField(blank=True, null=True, verbose_name='Previous End Date')),
                ('previous_end_time', models.TimeField(blank=True, null=True, verbose_name='Previous End Time')),
                ('new_start_date', models.DateField(blank=True, null=True, verbose_name='New Start Date')),
                ('new_start_time', models.TimeField(blank=True, null=True, verbose_name='New Start Time')),
                ('new_end_date', models.DateField(blank=True, null=True, verbose_name='New End Date')),
                ('new_end_time', models.TimeField(blank=True, null=True, verbose_name='New End Time')),
                ('changed_fields', models.JSONField(default=list, help_text='List of field names that were actually modified.', verbose_name='Changed Fields')),
                ('reason', models.TextField(blank=True, help_text='Optional reason provided by the user for the change.', null=True, verbose_name='Reason')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Changed At')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_datetime_changes', to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datetime_change_logs', to='hrms_app.usertour', verbose_name='Tour')),
            ],
            options={
                'verbose_name': 'Tour Date/Time Change Log',
                'verbose_name_plural': 'Tour Date/Time Change Logs',
                'ordering': ['-changed_at'],
            },
        ),
    ]
