# Generated by Django 4.2.16 on 2026-06-24 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0039_tourdatetimechangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Only selected users can use this setting. Leave blank to allow all users.', related_name='allowed_app_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tourdatetimechangelog',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tourdatetimechangelog',
            name='changed_fields',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='tourdatetimechangelog',
            name='new_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourdatetimechangelog',
            name='new_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourdatetimechangelog',
            name='new_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourdatetimechangelog',
            name='new_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourdatetimechangelog',
            name='previous_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourdatetimechangelog',
            name='previous_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourdatetimechangelog',
            name='previous_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourdatetimechangelog',
            name='previous_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourdatetimechangelog',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Reason'),
        ),
    ]
