# Generated by Django 4.2.16 on 2026-08-19 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hrms_app.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0040_appsetting_allowed_users_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emailotp',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this attendance log entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='attendancesetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='attendancesetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='compensatoryoff',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the department was created.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_by',
            field=models.ForeignKey(help_text='The user who created this department.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when the department was last updated.', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='department',
            name='updated_by',
            field=models.ForeignKey(help_text='The user who last updated this department.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when the designation was last updated.', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='formprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='formprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='applyingDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Applying Date'),
        ),
        migrations.AlterField(
            model_name='leavebalanceopenings',
            name='year',
            field=models.PositiveIntegerField(default=hrms_app.models._current_year),
        ),
        migrations.AlterField(
            model_name='maritalstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='officelocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='officelocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_detail', to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
